[versions]
minecraft = "1.21.8"
minecraft-parchment = "1.21.8"
parchment = "2025.07.20"

# Xplat
neoform = "1.21.8-20250717.133445"
mixin = "0.15.5+mixin.0.8.7"
mixin-extras = "0.4.1"

# Fabric
fabric-loader = "0.16.14"
fabric-api = "0.133.0+1.21.8"
mod-menu = "15.0.0"

# NeoForge
neoforge = "21.8.39"

# Gradle
loom = "1.11.+"
moddev = "2.0.105"
mod-publish = "0.8.4"

[libraries]
minecraft = { module = "com.mojang.:minecraft", version.ref = "minecraft" }
parchment = { module = "org.parchmentmc.data:parchment-1.21.8", version.ref = "parchment" }

mixin = { module = "net.fabricmc:sponge-mixin", version.ref = "mixin" }
mixin-extras = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixin-extras" }

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
mod-menu = { module = "com.terraformersmc:modmenu", version.ref = "mod-menu" }

neoforge-test-framework = { module = "net.neoforged:testframework", version.ref = "neoforge" }

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }
moddev = { id = "net.neoforged.moddev", version.ref = "moddev" }
mod-publish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod-publish" }
